# Use the existing guacamole/guacamole image as the base
FROM guacamole/guacamole:latest

# Example customization of branding, but do any other customizations here
COPY branding.jar /opt/guacamole/extensions/branding.jar
ENV GUACAMOLE_HOME=/opt/guacamole
